name: Build java-cef 5359

on: [workflow_dispatch]

jobs:
  java-cef-linux-amd64:
    runs-on: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v3
      - run: |
          ls -al
          sudo apt update
          sudo apt install build-essential g++ cmake ninja-build openjdk-17-jdk python3 libgtk2.0-dev -y
          mkdir jcef_build && cd jcef_build
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          export JAVA_INCLUDE_PATH=/usr/lib/jvm/java-17-openjdk-amd64/include
          cmake -G "Ninja" -DPROJECT_ARCH=amd64 -DCMAKE_BUILD_TYPE=Release ..
          ninja -j4
          mv native/Release native/linux_amd64
          strip native/linux_amd64/libcef.so
          tar -czf linux_amd64.tar.gz -C native . 
          ls -al
          pwd
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-amd64
          path: /home/runner/work/java-cef/java-cef/jcef_build/linux_amd64.tar.gz
  java-cef-linux-arm64:
    runs-on: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v3
      - run: |
          ls -al
          sudo apt update
          sudo apt install build-essential g++ cmake ninja-build openjdk-17-jdk python3 libgtk2.0-dev -y
          mkdir jcef_build && cd jcef_build
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          export JAVA_INCLUDE_PATH=/usr/lib/jvm/java-17-openjdk-amd64/include
          cmake -G "Ninja" -DPROJECT_ARCH=arm64 -DCMAKE_BUILD_TYPE=Release ..
          ninja -j4
          mv native/Release native/linux_arm64
          strip native/linux_arm64/libcef.so
          tar -czf linux_arm64.tar.gz -C native . 
          ls -al
          pwd
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-arm64
          path: /home/runner/work/java-cef/java-cef/jcef_build/linux_arm64.tar.gz
  java-cef-windows-amd64:
    runs-on: [windows-2022]
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
      - run: |
          dir
          mkdir jcef_build && cd jcef_build
          cmake -G "Ninja" -DPROJECT_ARCH=amd64 -DCMAKE_BUILD_TYPE=Release ..
          ninja -j4
          cd native
          ren Release windows_amd64
          cd ..
          tar -czf windows_amd64.tar.gz -C native . 
          dir
          cd
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-amd64
          path: D:\a\java-cef\java-cef\jcef_build\windows_amd64.tar.gz
  java-cef-windows-arm64:
    runs-on: [windows-2022]
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
      - run: |
          dir
          mkdir jcef_build && cd jcef_build
          cmake -G "Ninja" -DPROJECT_ARCH=arm64 -DCMAKE_BUILD_TYPE=Release ..
          ninja -j4
          cd native
          ren Release windows_arm64
          cd ..
          tar -czf windows_arm64.tar.gz -C native . 
          dir
          cd
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-arm64
          path: D:\a\java-cef\java-cef\jcef_build\windows_arm64.tar.gz
  java-cef-macos-amd64:
    runs-on: [macos-12]
    steps:
      - uses: actions/checkout@v3
      - run: |
          ls -al
          brew install ninja
          sudo xcode-select --switch /Applications/Xcode_13.1.app
          mkdir jcef_build && cd jcef_build
          cmake -G "Ninja" -DPROJECT_ARCH=amd64 -DCMAKE_BUILD_TYPE=Release ..
          ninja -j4
          mv native/Release native/macos_amd64
          tar -czf macos_amd64.tar.gz -C native . 
          ls -al
          pwd
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-amd64
          path: /Users/runner/work/java-cef/java-cef/jcef_build/macos_amd64.tar.gz
  java-cef-macos-arm64:
    runs-on: [macos-12]
    steps:
      - uses: actions/checkout@v3
      - run: |
          ls -al
          brew install ninja
          sudo xcode-select --switch /Applications/Xcode_13.1.app
          mkdir jcef_build && cd jcef_build
          cmake -G "Ninja" -DPROJECT_ARCH=arm64 -DCMAKE_BUILD_TYPE=Release ..
          ninja -j4
          mv native/Release native/macos_arm
          tar -czf macos_arm64.tar.gz -C native . 
          ls -al
          pwd
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-arm64
          path: /Users/runner/work/java-cef/java-cef/jcef_build/macos_arm64.tar.gz
